"""Adjusting table user and lead

Revision ID: 842356921de7
Revises: 7e5fa68d5d2a
Create Date: 2022-05-17 21:07:39.886876

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "842356921de7"
down_revision = "7e5fa68d5d2a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "lead",
        "email",
        existing_type=mysql.VARCHAR(length=15),
        type_=sa.String(length=60),
        nullable=False,
    )
    op.alter_column(
        "user", "email", existing_type=mysql.VARCHAR(length=60), nullable=False
    )
    op.alter_column(
        "user",
        "hashed_password",
        existing_type=mysql.VARCHAR(length=255),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user",
        "hashed_password",
        existing_type=mysql.VARCHAR(length=255),
        nullable=True,
    )
    op.alter_column(
        "user", "email", existing_type=mysql.VARCHAR(length=60), nullable=True
    )
    op.alter_column(
        "lead",
        "email",
        existing_type=sa.String(length=60),
        type_=mysql.VARCHAR(length=15),
        nullable=True,
    )
    # ### end Alembic commands ###
