name: Gym Movement CI

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9.6

    - name: Install poetry
      uses: snok/install-poetry@v1.2.0
      with:
        version: 1.1.12
        virtualenvs-create: false
        virtualenvs-in-project: false

    - name: Install pre-commit
      run: |
        pip install pre-commit && pip install setuptools

    - name: Run pre-commit
      run: |
        poetry run pre-commit run --all-files
